package com.urlshortener.createshorturl.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotEmpty;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "ShortenedUrlInformation")
public class ShortenedUrlInformation {

    public ShortenedUrlInformation(@NotEmpty(message = "{longUrl.notEmpty}") String longUrl, String shortUrl) {
        this.longUrl = longUrl;
        this.shortUrl = shortUrl;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @NotEmpty(message = "{longUrl.notEmpty}")
    private String longUrl;

    @DynamoDBAttribute
    private String shortUrl;

}
